###############################################################################
# DPS8M Proxy - .gitlab-ci.yml
# Copyright (c) 2025 Jeffrey H. Johnson
# Copyright (c) 2025 The DPS8M Development Team
# SPDX-License-Identifier: MIT-0
# scspell-id: 1fa03764-6c0f-11f0-adcf-80ee73e9b8e7
###############################################################################

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 0

###############################################################################

before_script:
  - apk update || true
  - apk add git
  - git fetch origin
  - git checkout -B "$CI_COMMIT_REF_NAME" "origin/$CI_COMMIT_REF_NAME"

###############################################################################

pages:
  stage: deploy
  image: alpine:edge
  tags:
    - saas-linux-2xlarge-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - apk update || true
    - apk add '!usr-merge-nag' 2> /dev/null || true
    - apk upgrade --prune || true
    - apk add brotli curl gawk git go grep pdpmake perl pigz py3-pip python3 sed shellcheck tree yash zip
    - ln -fs "$(command -v yash)" /bin/sh
    - export SHELL=/bin/sh
    - export PATH=$HOME/go/bin:$PATH
    - export GOPROXY=proxy.golang.org,direct
    - export GOSUMDB=sum.golang.org
    - export GOTOOLCHAIN="$(grep '^go .*$' go.mod | tr -cd 'go0-9.\n')+auto"
    - export PDPMAKE_POSIXLY_CORRECT=1
    - export TZ=UTC
    - export MS_GOTOOLCHAIN_TELEMETRY_ENABLED=0
    - go telemetry off || true
    - yash ./.lintsetup.sh
    - python3 -m venv $(pwd)/.venv
    - . $(pwd)/.venv/bin/activate
    - pip install --upgrade pip || true
    - pip install --upgrade scspell3k codespell reuse
    - env CI_NO_CROSS=1 pdpmake lint
    - git diff --exit-code
    - env GOFLAGS="-ldflags=-s -w" pdpmake
    - env GOFLAGS="-ldflags=-s -w" pdpmake cross
    - mv -f cross.bin public
    - cd public
    - for i in proxy.windows.*; do [ -f "${i:?}" ] || continue; mv -f -- "${i:?}" "${i:?}.exe"; done
    - for f in proxy.windows.*.exe; do [ -f "${f:?}" ] || continue; base="${f%.exe}"; zipname="$(printf '%s\n' "${base:?}" | awk -F. '{ for (i = 1; i < NF; i++) printf "%s-", $i; print $NF ".zip" }')"; (go version -m "${f:?}" || printf '%s\n' ".") | zip -z9 "${zipname:?}" "${f:?}"; done && rm -f *.exe
    - find . -name 'proxy.*' -print0 | xargs -0 -I{} -P $(nproc) sh -c 'pigz -C "$(go version -m {} | tr -d \" || true)" -MN9 "{}"'
    - tree -H 'https://dps8m.gitlab.io/proxy/' -L 1 --charset utf-8 -h -F -v -P 'proxy*' --metafirst -o index.html
    - sed -i 's#<a href="https://dps8m.gitlab.io/proxy/./">.</a>#<a href="https://gitlab.com/dps8m/proxy/">Home</a>#' index.html
    - sed -i "s#>Directory Tree<#>$(../proxy --version | head -1 | cut -d '[' -f 1 | sed 's/ g[[:xdigit:]][[:xdigit:]]*)/)/')<#g" index.html
    - sed -i '/<p class="VERSION">/,/<\/p>/d' index.html
    - sed -i 's#4\.0K#....#' index.html
    - find . -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec brotli -f -k -v -Z -- "{}" \; || true
    - find . -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec pigz -9 -f -k -m -v -- "{}" \; || true
    - cd ..
    - go mod download || true
    - go mod vendor || true
  artifacts:
    expire_in: 1 day
    paths:
      - public
      - vendor
  retry: 2
  timeout: 60 minutes
  interruptible: false

###############################################################################
