# Copyright (c) 2025 Jeffrey H. Johnson
# SPDX-License-Identifier: MIT-0
# scspell-id: 1fa03764-6c0f-11f0-adcf-80ee73e9b8e7
pages:
  stage: deploy
  image: alpine:edge
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - apk update
    - apk -U upgrade --prune || true
    - apk -U add brotli curl gawk git go grep make pdpmake perl pigz py3-pip python3 sed shellcheck tree yash zip
    - ln -fs "$(command -v yash)" /bin/sh
    - export SHELL=/bin/sh
    - export PATH=$HOME/go/bin:$PATH
    - export GOTOOLCHAIN="$(grep '^go .*$' go.mod | tr -cd 'go0-9.\n')+auto"
    - export PDPMAKE_POSIXLY_CORRECT=1
    - go install github.com/boyter/scc/v3@master
    - go install github.com/kisielk/errcheck@master
    - go install github.com/mgechev/revive@master
    - go install honnef.co/go/tools/cmd/staticcheck@master
    - go install mvdan.cc/gofumpt@master
    - go install mvdan.cc/sh/v3/cmd/shfmt@master
    - curl -fsSL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | yash -s -- -b $(go env GOPATH)/bin latest
    - python3 -m venv $(pwd)/.venv
    - . $(pwd)/.venv/bin/activate
    - pip install --upgrade pip || true
    - pip install --upgrade scspell3k
    - pip install --upgrade codespell
    - pip install --upgrade reuse
    - env CI_NO_CROSS=1 pdpmake lint
    - git restore README.md || true
    - git diff --exit-code
    - env GOFLAGS="-ldflags=-s -w" pdpmake cross
    - mv -f cross.bin public
    - cd public
    - for i in proxy.windows.*; do [ -f "${i:?}" ] || continue; mv -f -- "${i:?}" "${i:?}.exe"; done
    - for f in proxy.windows.*.exe; do [ -f "${f:?}" ] || continue; base="${f%.exe}"; zipname="$(echo "${base:?}" | awk -F. '{ for (i = 1; i < NF; i++) printf "%s-", $i; print $NF ".zip" }')"; (go version -m "${f:?}" || echo .) | zip -z9 "${zipname:?}" "${f:?}"; done && rm -f *.exe
    - find . -name 'proxy.*' -print0 | xargs -0 -I{} -P $(nproc) sh -c 'pigz -C "$(go version -m {} | tr -d \" || true)" -MN9 "{}"'
    - tree -H '.' -L 1 --charset utf-8 -h -F -v -P 'proxy*' --metafirst -o index.html
    - sed -i 's#<a href="../">.</a>#<a href="https://gitlab.com/dps8m/proxy/">Home</a>#' index.html
    - sed -i 's#>Directory Tree<#>DPS8M Proxy<#g' index.html
    - sed '/<p class="VERSION">/,/<\/p>/d' index.html > clean.html && mv -f clean.html index.html
    - find . -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec brotli -f -k -v -Z -- "{}" \; || true
    - find . -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec pigz -9 -f -k -m -v -- "{}" \; || true
  artifacts:
    expire_in: 1 day
    paths:
      - public
  retry: 2
  timeout: 60 minutes
  interruptible: false
