# Copyright (c) 2025 Jeffrey H. Johnson
# Copyright (c) 2025 The DPS8M Development Team
# SPDX-License-Identifier: MIT-0
# scspell-id: 53256192-6bd1-11f0-b70d-80ee73e9b8e7
linters:
  enable-all: true
  disable:
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - ireturn
    - maintidx
    - mnd
    - nestif
    - perfsprint
    - tenv
    - varnamelen
    - wrapcheck
    - wsl
