###############################################################################
# DPS8M Proxy - .golangci.yml
# Copyright (c) 2025 Jeffrey H. Johnson
# Copyright (c) 2025 The DPS8M Development Team
# SPDX-License-Identifier: MIT-0
# scspell-id: 53256192-6bd1-11f0-b70d-80ee73e9b8e7
###############################################################################

version: "2"
linters:
  default: all
  disable:
    - containedctx
    - contextcheck
    - cyclop
    - err113
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - maintidx
    - mnd
    - nestif
    - noctx
    - varnamelen
    - wsl
    - wsl_v5
  exclusions:
    generated: lax
    paths:
      - builtin$
      - examples$
      - third_party$
  settings:
    depguard:
      rules:
        main:
          files:
            - $all
          allow:
            - $gostd
            - github.com/arl/statsviz
            - github.com/google/gops/agent
            - github.com/hashicorp/mdns
            - github.com/klauspost/compress/gzip
            - github.com/klauspost/compress/zstd
            - github.com/sorairolake/lzip-go
            - github.com/spf13/pflag
            - github.com/ulikunitz/xz
            - go.etcd.io/bbolt
            - golang.org/x/crypto/ssh
            - golang.org/x/sys/unix
            - golang.org/x/term
            - go.uber.org/goleak
            - kernel.org/pub/linux/libs/security/libcap/cap
          deny:
            - pkg: io/ioutil
              desc: "Deprecated: see https://pkg.go.dev/io/ioutil for details"
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
  exclusions:
    generated: lax
    paths:
      - builtin$
      - examples$
      - third_party$
