##############################################################################
# DPS8M Proxy - fail2ban/jail.d/dps8m-proxy.conf
# Copyright (c) 2026 Jeffrey H. Johnson
# Copyright (c) 2026 The DPS8M Development Team
# SPDX-License-Identifier: MIT-0
# scspell-id: 96ac1a8e-5648-11f1-bf4a-80ee73e9b8e7
##############################################################################

[dps8m-proxy]
enabled = true
filter = dps8m-proxy
logpath = /home/dps8m-proxy/log/console.log
maxretry = 1
findtime = 600
bantime = 3600

##############################################################################
# Local Variables:
# mode: conf-windows
# indent-tabs-mode: t
# tab-width: 4
# fill-column: 78
# eval: (setq-local display-fill-column-indicator-column 78)
# eval: (display-fill-column-indicator-mode 1)
# End:
##############################################################################
# vim: set ft=dosini noexpandtab ts=4 cc=78 :
##############################################################################
